services:
  users1:
    build: ./users
    environment:
      INSTANCE: users-1

  users2:
    build: ./users
    environment:
      INSTANCE: users-2

  products:
    build: ./products
    environment:
      INSTANCE: products-1

  orders1:
    build: ./orders
    environment:
      INSTANCE: orders-1

  orders2:
    build: ./orders
    environment:
      INSTANCE: orders-2

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - users1
      - users2
      - products
      - orders1
      - orders2