services:
  postgres:
    image: postgres:16
    container_name: postgres_universidad
    environment:
      POSTGRES_DB: universidad
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_data: